✨ feat: 支持配置是否在首页显示自定义内容
arvinxx/dumi-theme-antd-style pull request #105
Opened 2024-02-19 02:14 UTC by FriedRiceNoodles

#### 💻 变更类型 | Change Type

- \[x] ✨ feat
- \[ ] 🐛 fix
- \[ ] 💄 style
- \[ ] 🔨 chore
- \[ ] 📝 docs

#### 🔀 变更说明 | Description of Change

close https://github.com/arvinxx/dumi-theme-antd-style/issues/104

现在可以直接在index.md中编写markdown内容和代码，用于自定义首页了。

![img_v3_0287_ef896ff4-82fa-4f92-957d-1725fe4a1b3g](https://github.com/arvinxx/dumi-theme-antd-style/assets/53017934/5ea13241-9f5d-47b2-80fe-63f344415853)
![img_v3_0287_2e317eb8-7cad-419d-84a6-d4877d442b0g](https://github.com/arvinxx/dumi-theme-antd-style/assets/53017934/f4f29e5c-07ff-4d4d-8520-b2f60f5c127a)

BTW：
1. CI流程好像挂了？如果合并了之后可以发个新版本吗，想用到这个特性
2. 仓库内似乎没有配置commitizen？这次的commit msg是复制来的。

2024-02-19 02:50 UTC, arvinxx requested changes

2024-02-19 02:50 UTC, arvinxx commented on src/pages/Home/index.tsx
> +        <div className={styles.container}>{outlet}</div>
这个行为和现有的 index.md 是 Breaking Change ，建议通过一个配置开启，默认不开启

2024-02-19 02:54 UTC, arvinxx commented on src/pages/Home/index.tsx
> +        <div className={styles.container}>{outlet}</div>
这样的话，那个 embed 也就不用删掉了

2024-02-19 02:55 UTC, FriedRiceNoodles commented on src/pages/Home/index.tsx
> +        <div className={styles.container}>{outlet}</div>
> 这样的话，那个 embed 也就不用删掉了

话说这个embed原本是有作用的吗，它本来好像也不会显示的样子

2024-02-19 02:57 UTC, arvinxx commented on src/pages/Home/index.tsx
> +        <div className={styles.container}>{outlet}</div>
embed 在 dumi 默认主题下是会正常显示的，我之前没删的目的就是为了验证不显示自定义markdown

2024-02-19 05:59 UTC, arvinxx commented on example/docs/index.en-US.md
这两个变更revert下

2024-02-19 07:14 UTC, arvinxx commented on src/store/selectors/hero.ts
> +  !!s.routeMeta.frontmatter.hero?.showCustomContent;
这个的配置好像不是在 ThemeConfig 上的？像是在 index.md 上的 frontmatter ？ 如果是这样的话感觉 配置的介绍写的有点问题?

2024-02-23 09:09 UTC, Wxh16144 commented
感觉可以默认开启这个功能，这个功能属于增量更新🤔

2024-02-23 11:26 UTC, merged